In [2]:
import torch

In [8]:
# torch.tensor?

In [3]:
t1 = torch.tensor([1, 2, 3, 4, 5])

In [4]:
t1.shape

torch.Size([5])

In [5]:
t2 = t1

In [6]:
t1 is t2

True

In [ ]:
t2 = t1.clone().detach()

In [9]:
## sytanx tree -> autograd -> gradient tracking
t3 = t1

In [10]:
t3

tensor([1, 2, 3, 4, 5])

In [13]:
t4 = torch.rand(10)

In [14]:
t4

tensor([0.1173, 0.5676, 0.0436, 0.5495, 0.1025, 0.0163, 0.4225, 0.5239, 0.9700,
        0.1549])

In [16]:
t4

tensor([0.1173, 0.5676, 0.0436, 0.5495, 0.1025, 0.0163, 0.4225, 0.5239, 0.9700,
        0.1549])

In [17]:
t5 = t4

In [20]:
t5[0] = .2000

In [21]:
t4

tensor([0.2000, 0.5676, 0.0436, 0.5495, 0.1025, 0.0163, 0.4225, 0.5239, 0.9700,
        0.1549])

In [22]:
t6 = t4.clone()

In [23]:
t4

tensor([0.2000, 0.5676, 0.0436, 0.5495, 0.1025, 0.0163, 0.4225, 0.5239, 0.9700,
        0.1549])

In [24]:
t6

tensor([0.2000, 0.5676, 0.0436, 0.5495, 0.1025, 0.0163, 0.4225, 0.5239, 0.9700,
        0.1549])

In [25]:
t4[0] = 0.3000

In [26]:
t4

tensor([0.3000, 0.5676, 0.0436, 0.5495, 0.1025, 0.0163, 0.4225, 0.5239, 0.9700,
        0.1549])

In [27]:
t6

tensor([0.2000, 0.5676, 0.0436, 0.5495, 0.1025, 0.0163, 0.4225, 0.5239, 0.9700,
        0.1549])

In [28]:
t7 = torch.rand((6, 4))

In [29]:
t7.shape

torch.Size([6, 4])

In [30]:
t7

tensor([[0.0477, 0.8593, 0.9520, 0.3755],
        [0.7120, 0.2532, 0.5135, 0.0199],
        [0.0445, 0.1332, 0.1136, 0.2704],
        [0.1273, 0.1326, 0.7362, 0.7403],
        [0.4417, 0.0671, 0.7150, 0.5752],
        [0.0727, 0.1662, 0.4482, 0.3280]])

In [31]:
t7[0]

tensor([0.0477, 0.8593, 0.9520, 0.3755])

In [33]:
t7[:, 0]

tensor([0.0477, 0.7120, 0.0445, 0.1273, 0.4417, 0.0727])

In [35]:
t7[2, 3]

tensor(0.2704)

In [37]:
t7.is_contiguous()

True

In [41]:
t7.reshape(2, 3, 4).permute(1,0,2).is_contiguous()

False

In [42]:
## .view/ .reshape (costly)
## dimensions alter

t7.shape

torch.Size([6, 4])

In [44]:
t7

tensor([[0.0477, 0.8593, 0.9520, 0.3755],
        [0.7120, 0.2532, 0.5135, 0.0199],
        [0.0445, 0.1332, 0.1136, 0.2704],
        [0.1273, 0.1326, 0.7362, 0.7403],
        [0.4417, 0.0671, 0.7150, 0.5752],
        [0.0727, 0.1662, 0.4482, 0.3280]])

In [46]:
t7.view(3,8)

tensor([[0.0477, 0.8593, 0.9520, 0.3755, 0.7120, 0.2532, 0.5135, 0.0199],
        [0.0445, 0.1332, 0.1136, 0.2704, 0.1273, 0.1326, 0.7362, 0.7403],
        [0.4417, 0.0671, 0.7150, 0.5752, 0.0727, 0.1662, 0.4482, 0.3280]])

In [47]:
t7.reshape(2, 3, 4).permute(1,0,2).view(-1)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [51]:
## image -> 
t7.shape, t7.dim()

(torch.Size([6, 4]), 2)

In [53]:
t7.dim()

2

In [54]:
## C
int(2.65)

2

In [55]:
## 24 = 2*3*4
## 2*3*2*2
## 2*12
t8 = t7.clone()

In [56]:
x = (2, 10)

In [60]:
# range?

In [59]:
range(*x)

range(2, 10)

In [62]:
t9 = t8.reshape(2, 3, 4).clone()

In [63]:
## pytorch : channel , height , width -> bchw form -> batch channel height width
## numpy: height, width , channel -> bhwc -> batch height width channel

t9

tensor([[[0.0477, 0.8593, 0.9520, 0.3755],
         [0.7120, 0.2532, 0.5135, 0.0199],
         [0.0445, 0.1332, 0.1136, 0.2704]],

        [[0.1273, 0.1326, 0.7362, 0.7403],
         [0.4417, 0.0671, 0.7150, 0.5752],
         [0.0727, 0.1662, 0.4482, 0.3280]]])

In [64]:
t9.permute(1, 0, 2)

tensor([[[0.0477, 0.8593, 0.9520, 0.3755],
         [0.1273, 0.1326, 0.7362, 0.7403]],

        [[0.7120, 0.2532, 0.5135, 0.0199],
         [0.4417, 0.0671, 0.7150, 0.5752]],

        [[0.0445, 0.1332, 0.1136, 0.2704],
         [0.0727, 0.1662, 0.4482, 0.3280]]])

In [65]:
t10 = torch.randn(48)

In [66]:
## pause -> einops
## dot product 
## matmul 
## @ 

v1 = torch.tensor([1,2,3])
v2 = torch.tensor([3,4,5])

In [67]:
v1.dot(v2)

tensor(26)

In [68]:
v1 @ v2

tensor(26)

In [69]:
## dot product
## correlation
## cosine similarity
# -1 to +1

## king -> queen

In [70]:
## einops

In [73]:
from einops import rearrange, reduce, repeat

In [74]:
rearrange

<function einops.einops.rearrange(tensor: Union[~Tensor, List[~Tensor]], pattern: str, **axes_lengths: Any) -> ~Tensor>

In [81]:
t10.reshape(2, 6, 4).shape

torch.Size([2, 6, 4])

In [80]:
rearrange(t10, '(c h w) -> c h w', c=2, h=6, w=4).shape

torch.Size([2, 6, 4])

In [82]:
t11 = torch.rand(2,3)

In [83]:
t11

tensor([[0.1689, 0.3152, 0.8143],
        [0.6131, 0.1516, 0.7866]])

In [84]:
t11.reshape(3, 2)

tensor([[0.1689, 0.3152],
        [0.8143, 0.6131],
        [0.1516, 0.7866]])

In [87]:
t11

tensor([[0.1689, 0.3152, 0.8143],
        [0.6131, 0.1516, 0.7866]])

In [ ]:
rearrange(t11, 'a b -> b a')

tensor([[[0.1689, 0.6131],
         [0.3152, 0.1516],
         [0.8143, 0.7866]]])

In [88]:
t12 = torch.rand(20)

In [89]:
t12.shape

torch.Size([20])

In [90]:
t12.dim()

1

In [92]:
rearrange(t12, '(a b) -> a b', a=10)

tensor([[0.5129, 0.4815],
        [0.2047, 0.9640],
        [0.6783, 0.5440],
        [0.4826, 0.7099],
        [0.5265, 0.4578],
        [0.4212, 0.0541],
        [0.0607, 0.8239],
        [0.1463, 0.3816],
        [0.6514, 0.1685],
        [0.3056, 0.3220]])

In [93]:
x = torch.tensor([1, 2, 3, 4, 5])

In [98]:
x.unsqueeze(dim=0).unsqueeze(dim=0)

tensor([[[1, 2, 3, 4, 5]]])

In [99]:
## reduce X 
## ghanghor ghata ka ghamand ghata -> yamak alankar -> 
## 

t9.shape

torch.Size([2, 3, 4])

In [102]:
t12 = torch.arange(12)

In [103]:
t12

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
t13 = t12.reshape(3, 4)

In [112]:
t13

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [113]:
t13.sum(dim=0)
## 0 -> mere ko ye row batao jisme colum ka sum hai
## 1 -> mere ko ye col batao jisme row ka sum hai

tensor([12, 15, 18, 21])

In [114]:
t13.sum(dim=1)

tensor([ 6, 22, 38])

In [115]:
reduce(t13, 'a b -> a', 'sum')

tensor([ 6, 22, 38])

In [116]:
reduce(t13 , 'a b -> b', 'sum')

tensor([12, 15, 18, 21])

In [119]:
t9.shape

torch.Size([2, 3, 4])

In [120]:
t9

tensor([[[0.0477, 0.8593, 0.9520, 0.3755],
         [0.7120, 0.2532, 0.5135, 0.0199],
         [0.0445, 0.1332, 0.1136, 0.2704]],

        [[0.1273, 0.1326, 0.7362, 0.7403],
         [0.4417, 0.0671, 0.7150, 0.5752],
         [0.0727, 0.1662, 0.4482, 0.3280]]])

In [127]:
t13 = torch.tensor([[[1,2,3], [4, 5, 6]], [[11,12,13], [14, 15, 16]]])

In [128]:
t13.shape

torch.Size([2, 2, 3])

In [129]:
t13

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 12, 13],
         [14, 15, 16]]])

In [130]:
t13.permute(1,0,2)

tensor([[[ 1,  2,  3],
         [11, 12, 13]],

        [[ 4,  5,  6],
         [14, 15, 16]]])

In [131]:
t13.permute(0,2,1)

tensor([[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],

        [[11, 14],
         [12, 15],
         [13, 16]]])